#!/usr/bin/env bash

SERVER="http://localhost:8000/messages"
TARGET="some_target"

get_range() {
    START="$1"
    END="$2"
    curl -i -XGET "${SERVER}/${TARGET}?start=$START&end=$END"
}

get_unread() {
    curl -i -XGET "${SERVER}/${TARGET}"
}

post() {
    JSON="$1"
    curl -i -H "Content-Type: application/json" -XPOST "${SERVER}/${TARGET}" -d "$JSON"
}

delete() {
    JSON="$1"
    curl -i -H "Content-Type: application/json" -XDELETE "${SERVER}/${TARGET}" -d "$JSON"
}


case "$1" in
    get_range)
        get_range "$2" "$3"
        ;;
    get_unread)
        get_unread
        ;;
    post)
        post "$2"
        ;;
    delete)
        delete "$2"
        ;;
    *)
        echo "Usage: $0 {get_range, get_unread, post, delete}"
        exit 1
esac
